
<script setup lang="ts">
import { ref } from 'vue';
import { useGlobalLoadingState } from '../../stores/admin-panel/global_loading_state.js';

const global_loading_state = useGlobalLoadingState();


</script>


<template>
  <div :class="global_loading_state.is_loading() ? ['z-[100]'] : ['z-[-100]', 'opacity-0']" class=" fixed top-0 left-0  h-screen bg-gray-700
  transition-all duration-150">
    <div class="z-[110] relative flex justify-center items-center w-screen h-screen overflow-hidden">
      <div class="text-[20vh] text-gray-400 overflow-hidden">
        <!-- <i class="fa-solid fa-hourglass-half"></i> -->

        <div class="loadingio-spinner-bars-819h66ozjab">
          <div class="ldio-lnebgfd2xih">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
          </div>
        </div>

      </div>
    </div>
  </div>
</template>

<style scoped>
@keyframes ldio-lnebgfd2xih {
  0% {
    opacity: 1
  }

  50% {
    opacity: .5
  }

  100% {
    opacity: 1
  }
}

.ldio-lnebgfd2xih div {
  position: absolute;
  width: 20px;
  height: 80px;
  top: 60px;
  animation: ldio-lnebgfd2xih 1s cubic-bezier(0.5, 0, 0.5, 1) infinite;
}

.ldio-lnebgfd2xih div:nth-child(1) {
  transform: translate(30px, 0);
  background: #1d3f72;
  animation-delay: -0.6s;
}

.ldio-lnebgfd2xih div:nth-child(2) {
  transform: translate(70px, 0);
  background: #5699d2;
  animation-delay: -0.4s;
}

.ldio-lnebgfd2xih div:nth-child(3) {
  transform: translate(110px, 0);
  background: #d8ebf9;
  animation-delay: -0.2s;
}

.ldio-lnebgfd2xih div:nth-child(4) {
  transform: translate(150px, 0);
  background: #71c2cc;
  animation-delay: -1s;
}

.loadingio-spinner-bars-819h66ozjab {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: rgba(241, 242, 243, 0);
}

.ldio-lnebgfd2xih {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0;
  /* see note above */
}

.ldio-lnebgfd2xih div {
  box-sizing: content-box;
}

/* generated by https://loading.io/ */
</style>